[package]
name = "mid2ptcop"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"

[dependencies]
ptcow.version = "0.4.0"
ptcow.default-features = false
midly = "0.5.3"
thiserror = "2.0.17"

[dev-dependencies]
clap.version = "4.5"
clap.features = ["derive"]
soundfont = "0.1.0"
